services:
  huntarr:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: huntarr
    ports:
      - "9705:9705"
    volumes: 
      - huntarr-config:/config
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - TZ=${TZ:-UTC}
    restart: unless-stopped

volumes:
  huntarr-config:
    name: huntarr-config